devtools::load_all("/Users/achazhardenberg/Library/CloudStorage/Dropbox/Repos/because")
eqs <- list(Y ~ X)
dat <- data.frame(Y = rnorm(100), X = rnorm(100))
fit <- because(eqs, data = dat, n.iter = 2000)
cat("Original call:\n")
print(fit$call)

cat("\nUpdating model...\n")
fit_new <- update(fit, engine = "numpyro", n.iter=100)
cat("Updated call:\n")
print(fit_new$call)
